# Generated by Django 3.2.4 on 2021-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_useraddress_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name'),
        ),
    ]
